### ISSUE TITLE
Discussion on DefineGrid

### ISSUE THREAD

**Issue by karhohs** [CellProfiler/examples#21]
The DefineGrid segmentation is heavily automated, in contrast to IdentifyPrimaryObjects that exposes many parameters. Is DefineGrid to specific? Do we have more test cases beyond this yeast patch example? I could see DefineGrid being simplified by looping an IdentifyPrimaryObjects module through the defined grid.

**Comment by AnneCarpenter** [comment]
I think it's probably not worth bothering to change this until someone has a project requiring a grid where the pipeline doesn't suffice. It's a rare situation.
